### ISSUE TITLE
Create a Routes Folder

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#10]
# Description
Create a routes directory that will house all of the routers. 

# Tasks
- [ ] - Create the folder
- [ ] - Place at the root of the project
- [ ] - Move (if any) all of the route related files to this directory.

# Constraint
Requires: 
- IDE
- Terminal Access
