### ISSUE TITLE
Create a Scripts Folder

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#11]
# Description
Create a Scripts directory that will house all of the scripts. These scripts help house the logic of how each web page should behave.

# Tasks
- [ ] - Create the folder
- [ ] - Place at the root of the project
- [ ] - Move (if any) all of the scripts related files to this directory.

# Constraint
Requires: 
- IDE
- Terminal Access
