### ISSUE TITLE
Create a Views Folder

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#12]
# Description
Create a Views directory that will house all of the views files. These view files will have the extension .ejs that will house css and html code to control the design of the website.

# Tasks
- [ ] - Create the folder
- [ ] - Place at the root of the project
- [ ] - Move (if any) all of the views related files to this directory.

# Constraint
Requires: 
- IDE
- Terminal Access
