### ISSUE TITLE
Create a Models Folder

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#13]
# Description
Create a models directory that will house all of the database related models. These models are essentially schemas that will determine how data is stored in our database.

# Tasks
- [ ] - Create the folder
- [ ] - Place at the root of the project
- [ ] - Move (if any) all of the models related files to this directory.

# Constraint
Requires: 
- IDE
- Terminal Access
