### ISSUE TITLE
Create a .github\workflows

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#14]
# Description
Create a workflows directory within a .github directory that will house all of the .yaml files. These .yaml files will help establish a CI/CD pipeline that will use later for unit testing.

# Tasks
- [ ] - Create the folder
- [ ] - Place at the root of the project
- [ ] - Move (if any) all of the .yaml related files to this directory.

# Constraint
Requires: 
- IDE
- Terminal Access
