### ISSUE TITLE
Create a __tests__ folder

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#15]
# Description
Create a __tests__ directory that will house all of the unit tests.

# Tasks
- [ ] - Create the folder
- [ ] - Place at the root of the project
- [ ] - Move (if any) all of the unit test related files to this directory.

# Constraint
Requires: 
- IDE
- Terminal Access
