### ISSUE TITLE
Create a Register Page

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#16]
/# Description
Create a Register Page using a React library set

# Tasks

- [ ] - Implement Insert functionality into a database by creating a register form that accepts a username, password, first name, last name and has a submit button.
- [ ] - Add React to the project
- [ ] - Create Username input box
- [ ] - Create Password input box
- [ ] - Create First Name input box
- [ ] - Create Last Name input box
- [ ] - Create "Login" button
- [ ] - Create Submit button

# Constraint
Requires: 
- React.js
