### ISSUE TITLE
Create User Schema

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#18]
# Description
Create a database.js that creates a user schema describing the required fields for a user to register in the database. Add the requirements to the document (see constraints)

# Tasks
- [ ] - Create a new schema named "userSchema"
- [ ] - Add an email key with string as the value
- [ ] - Add a password key with string as the value 
- [ ] - Add firstName key with string as the value
- [ ] - Add lastName key with string as the value 
- [ ] - Email and Password must be requirements for the schema
- [ ] - Add timestamps so the created date is store
- [ ] - Export the schema

# Constraints
Requires:
- Mongoose
- Express.js
