### ISSUE TITLE
Link MongoDB to server.js

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#19]
# Description
Create a link between your app.js and your MongoDB so that both can communicate when actions are taken. You will need to connect to the database using an API key then have the app listen for a specific port. 

# Tasks
- [ ] - Import Mongoose library
- [ ] - Create a variable named "uri" that will store the API key from MongoDB so it knows what to connect to 
- [ ] - Import the app from app.js
- [ ] - Create a function called "connect" that connects the uri variable to the app

# Constraints
Requires:
- Mongoose
- API Key from MongoDB
