### ISSUE TITLE
Create a Unit Test for the Database Server

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#20]
# Description
Create a unit test that will make sure our database is connecting properly and storing test values.

# Tasks
- [ ] - Create Unit Tests for "Get Users"
- [ ] - Create Unit Tests for "Set Users"
- [ ] - Create Unit Tests for "Update Users"

# Constraints
Requires:
- Super Test
- Jest
- Mongoose
- MongoDB API Key
