### ISSUE TITLE
Develop a login page

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#6]
/# Description
Create a Login Page using a React library set

# Tasks

- [ ] - Implement user authentication functionality by creating a login form that accepts a username, password and has a submit button.
- [ ] - Add React to the project
- [ ] - Create Username input box
- [ ] - Create Password input box
- [ ] - Create "Register" button
- [ ] - Create Submit button
- [ ] - Create "Remember Me" radio button

# Constraint
Requires: 
- React.js
