### ISSUE TITLE
Create an App.js

### ISSUE THREAD

**Issue by DevByDJ** [GoGitters-Inc/requirements-project#8]
# Description
Create an app.js that will act as the focal point of what the web application does. It will require middleware and nodemon.

# Tasks
- [ ] - Create a new file name "app.js"
- [ ] - Import server.js
- [ ] - Import the routers that will be used in the application.
- [ ] - Declare the routes needed to navigate the pages within the application.
- [ ] - Create basic middleware
- [ ] - Export the app module.

# Constraint
Requires: 
- IDE
- Terminal Access
